name: Build and Release Executables

on:
    workflow_dispatch:
        inputs:
            version:
                description: "ocr-reader version"
                required: true

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
          cache: 'pip'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: "latest"

      - name: Install the project dependencies
        run: uv sync

      - name: Build application
        run: |
          python -m pip install --upgrade pip PyQt5 PyInstaller opencv-python==4.9.0.80 numpy<2.0 pillow==11.3.0 pytesseract==0.3.13 sentencepiece==0.2.1 torch==2.2.2 transformers==4.39.3
          python -m PyInstaller --windowed src/app.py

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ocr-reader-${{ matrix.os }}
          path: dist/*