name: Build and Release Executables

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            version:
                description: "v0.0.1"
                required: true

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install the project
        run: uv sync

      - name: Build application
        run: |
          pyinstaller --onefile src/app.py

      - name: Rename executable
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/app.exe dist/ocr-reader-windows.exe
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            mv dist/app dist/ocr-reader-linux
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/app dist/ocr-reader-macos
          fi
        shell: bash

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ocr-reader-${{ matrix.os }}
          path: dist/*